name: case-studies-gravity
channels:
    - conda-forge
    - defaults
dependencies:
    - python=2.7
    - pip
    - numpy
    - scipy
    - pandas
    - xarray
    - numba
    - jupyter
    - ipython
    - ipywidgets
    - matplotlib
    - cartopy
    - cmocean=1.1
    - fatiando=0.5
